version: "3"
services:
  clash:
    image: metacubex/mihomo
    container_name: mihomo
    volumes:
      - ./config.yaml:/root/.config/mihomo/config.yaml
      - ./ui:/ui # dashboard volume
    ports:
      - 7890:7890
      - 7891:7891
      - 8080:8080 # external controller (Restful API)
    network_mode: host
    # TUN
    # cap_add:
    #   - NET_ADMIN
    # devices:
    #   - /dev/net/tun
    restart: unless-stopped
