version: '3'
services:
  web:
    image: whyour/qinglong:latest
    volumes:
      - ./data:/ql/data
    ports:
      - "0.0.0.0:5700:5700"
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:5400/api/health", "||", "exit", "1"]
      interval: 2m
      timeout: 10s
      retries: 3
